== Classes overview

This project contains 24 classes and 0 interface.

.Classes list
[cols="", %autowidth, frame=all, grid=all, stripes=none]
|===
|Classes |Interfaces

|<<Error-Prompt.lvclass>>
|

|<<Input (DBL).lvclass>>
|

|<<Input (I32).lvclass>>
|

|<<Input (String).lvclass>>
|

|<<One Button.lvclass>>
|

|<<Timeout One Button.lvclass>>
|

|<<Timeout Two Button.lvclass>>
|

|<<Timeout.lvclass>>
|

|<<Two Button.lvclass>>
|

|<<Custom - Input (DBL).lvclass>>
|

|<<Custom - Input (I32).lvclass>>
|

|<<Custom - Input (String).lvclass>>
|

|<<Custom - One Button.lvclass>>
|

|<<Custom - Timeout One Button.lvclass>>
|

|<<Custom - Timeout Two Button.lvclass>>
|

|<<Custom - Timeout.lvclass>>
|

|<<Custom - Two Button.lvclass>>
|

|<<PNG Parent.lvclass>>
|

|<<Plain - One Button.lvclass>>
|

|<<Plain - Two Button.lvclass>>
|

|<<Plain - Three Button.lvclass>>
|

|<<Plain Parent.lvclass>>
|

|<<Popup.lvclass>>
|

|<<Theme.lvclass>>
|
|===

[plantuml, format="svg", align="center"]
....
@startuml
set namespaceSeparator :
skinparam ClassBackgroundColor #FFFFFF
skinparam ClassBorderColor #555555
skinparam ClassFontColor #000000
skinparam ClassHeaderBackgroundColor #808080

skinparam top to bottom direction
class "Pop-Up.lvlib:Error-Prompt" {
{static} {method} +Display Error-Prompt()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Error-Prompt"


class "Pop-Up.lvlib:Input (DBL)" {
{field} -Input : Double Float
{static} {method} +Display Input (DBL) Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Input (DBL)"


class "Pop-Up.lvlib:Input (I32)" {
{field} -Input : I32
{static} {method} +Display Input (I32) Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Input (I32)"


class "Pop-Up.lvlib:Input (String)" {
{field} -Input : String
{field} -Display Style : U32
{static} {method} +Display Input (String) Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Input (String)"


class "Pop-Up.lvlib:One Button" {
{static} {method} +Display One Button Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:One Button"


class "Pop-Up.lvlib:Timeout One Button" {
{field} -Timeout (s) : Double Float
{field} -Button Text : String
{static} {method} +Display Timeout One Button Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Timeout One Button"


class "Pop-Up.lvlib:Timeout Two Button" {
{field} -YText : String
{field} -NText : String
{field} -Timeout (s) : Double Float
{static} {method} +Display Timeout Two Button Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Timeout Two Button"


class "Pop-Up.lvlib:Timeout" {
{field} -Timeout (s) : Double Float
{static} {method} +Display Timeout Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Timeout"


class "Pop-Up.lvlib:Two Button" {
{field} -YText : String
{field} -NText : String
{static} {method} +Display Two Button Popup()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Two Button"


class "Pop-Up.lvlib:Custom - Input (DBL)" {
{field} -Input : Double Float
{static} {method} +Display Input (DBL) Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Input (DBL)"


class "Pop-Up.lvlib:Custom - Input (I32)" {
{field} -Input : I32
{static} {method} +Display Input (I32) Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Input (I32)"


class "Pop-Up.lvlib:Custom - Input (String)" {
{field} -Input : String
{field} -Display Style : U32
{static} {method} +Display Input (String) Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Input (String)"


class "Pop-Up.lvlib:Custom - One Button" {
{static} {method} +Display One Button Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - One Button"


class "Pop-Up.lvlib:Custom - Timeout One Button" {
{field} -Timeout (s) : Double Float
{field} -Button Text : String
{static} {method} +Display Timeout One Button Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Timeout One Button"


class "Pop-Up.lvlib:Custom - Timeout Two Button" {
{field} -YText : String
{field} -NText : String
{field} -Timeout (s) : Double Float
{static} {method} +Display Timeout Two Button Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Timeout Two Button"


class "Pop-Up.lvlib:Custom - Timeout" {
{field} -Timeout (s) : Double Float
{static} {method} +Display Timeout Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Timeout"


class "Pop-Up.lvlib:Custom - Two Button" {
{field} -YText : String
{field} -NText : String
{static} {method} +Display Two Button Popup (Custom)()
{method} #Display()

}
"Pop-Up.lvlib:PNG Parent" <|-- "Pop-Up.lvlib:Custom - Two Button"


class "Pop-Up.lvlib:PNG Parent" {
{static} {method} -PNG Picture Setup()
{static} {method} -PNG Picture Size Reader()
{method} #Display()
{method} #Template Pattern - Caller()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:PNG Parent"


class "Pop-Up.lvlib:Plain - One Button" {
{static} {method} +Display One Button Popup (Plain)()
{method} #Display()

}
"Pop-Up.lvlib:Plain Parent" <|-- "Pop-Up.lvlib:Plain - One Button"


class "Pop-Up.lvlib:Plain - Two Button" {
{static} {method} +Display Two Button Popup (Plain)()
{method} #Display()

}
"Pop-Up.lvlib:Plain Parent" <|-- "Pop-Up.lvlib:Plain - Two Button"


class "Pop-Up.lvlib:Plain - Three Button" {
{field} -choice : U8
{static} {method} +Display Three Button Popup (Plain)()
{method} #Display()

}
"Pop-Up.lvlib:Plain Parent" <|-- "Pop-Up.lvlib:Plain - Three Button"


class "Pop-Up.lvlib:Plain Parent" {
{field} -Dialog Title : String
{field} -Action 1 Text : String
{field} -Action 2 Text : String
{field} -Action 3 Text : String
{field} -Transparent buttons? : Boolean
{static} {method} +Get Action 1 Text()
{static} {method} +Set Action 1 Text()
{static} {method} +Get Action 2 Text()
{static} {method} +Set Action 2 Text()
{static} {method} +Get Action 3 Text()
{static} {method} +Set Action 3 Text()
{static} {method} +Get Dialog Title()
{static} {method} +Set Dialog Title()
{static} {method} +Get Transparent buttons()
{static} {method} +Set Transparent buttons()
{method} #Display()

}
"Pop-Up.lvlib:Popup" <|-- "Pop-Up.lvlib:Plain Parent"


class "Pop-Up.lvlib:Popup" {
{field} #Message : String
{field} #Image : Picture
{field} #Choice : Boolean
{field} #Pic Width : I16
{field} #Pic Height : I16
{field} #pre-empt : NoType
{field} #Theme : LV Class
{field} #Message Size : Cluster
{field} -Timeout? : Boolean
{static} {method} #Check pre-empt -- Boolean()
{static} {method} #Check pre-empt -- DBL()
{static} {method} #Check pre-empt -- I32()
{static} {method} #Check pre-empt -- String()
{static} {method} #Check pre-empt()
{static} {method} #Close pre-empt()
{static} {method} #Create pre-empt()
{static} {method} #Close FP()
{static} {method} #Configure FP-Message-Image()
{static} {method} #Convert Enum to Image()
{static} {method} #Format Message - Embedded()
{static} {method} #Format Message - Strip Tags()
{static} {method} #LAVA.move picture()
{static} {method} #LAVA.Parse drawing operation()
{static} {method} #Move Button()
{static} {method} #Shift Input()
{static} {method} #Template Pattern - Display()
{static} {method} #Update FP and Show()
{static} {method} -Custom - Resize FP()
{static} {method} -Custom - Resize Pic and String()
{static} {method} +Close Pop-Up()
{static} {method} +Close Pop-Up (Two Button Choice)()
{static} {method} +Close Pop-Up (I32)()
{static} {method} +Close Pop-Up (DBL)()
{static} {method} +Close Pop-Up (String)()
{static} {method} +Format Message()
{method} #Template Pattern - Caller()
{method} #Display()

}
"Pop-Up.lvlib:Popup" *-- "Theme"


class "Theme" {
{field} -dialog colors : Cluster
{field} -button colors : Cluster
{field} -message font : Cluster
{field} -input : Cluster
{static} {method} +Apply Style - button()
{static} {method} +Apply Style - input()
{static} {method} +Apply Style - Simple Dialog()
{static} {method} +Apply Style()
{static} {method} +Set picture background()
{static} {method} +Construct Theme()
{static} {method} +Load Material Dialog()
{static} {method} +Load Theme - Light Gray()
{static} {method} +Load Theme - TSC Dark()
{static} {method} +Load Theme - TSC Light()
{static} {method} +Load Theme()
{static} {method} +Pick Button Hover()
{static} {method} +Pick Text Color()
{static} {method} ~priv-default theme()
{static} {method} +Reset Theme()
{static} {method} +Save Theme()
{static} {method} +Temp - Change Font()

}



@enduml
....
